### ISSUE TITLE
Is the firefox store extension added by you?

### ISSUE THREAD

**Issue by douglasg14b** [Bentlybro/GPTSearch#2]
Being wary of malicious add-ons, was this extension added by you, officially? https://addons.mozilla.org/en-US/firefox/addon/chatgpt-history-search-/

From what I can tell your code is not firefox compatible, if this was added by you, is there a firefox variant of this addon somewhere?

It's kinda sus that the permissions appear to be `Access your data for all websites` as opposed to just `chat.openai.com`

**Comment by Bentlybro** [comment]
yes i made that addon and it is compatible with firefox (i and several others are using it?) otherwise i would not of able add it to there store.

> It's kinda sus that the permissions appear to be `Access your data for all websites` as opposed to just `chat.openai.com`

i suppose so but all of the code is here so its not sus, you can see what its doing and no data is sent any where else other that the official chatgpt api, it was just easier to make it work this way (the perms), i can fix and update it but it wont really make any difference 

i just realised i did not add the firefox version of the code, i will get that uploaded here today so then you can have a look! (current code is for chome)

**Comment by Bentlybro** [comment]
Just uploaded the firefox version of the extension https://github.com/Bentlybro/GPTSearch/tree/main/GPTSearch%20-%20Firefox

And i updated the perms to be just for ``chat.openai.com`` 
by simply changing 
``"<all_urls>"`` to now just be ``"*://chat.openai.com/*"``
https://github.com/Bentlybro/GPTSearch/blob/a6fc8badb6861c2797536eb65a0f09f2a0c7d560/GPTSearch%20-%20Firefox/manifest.json#L9

**Comment by douglasg14b** [comment]
Thanks for the reply!

> otherwise i would not of able add it to there store.

I was more verifying that this was added by you, and not someone else impersonating you. Re-uploading browser extensions is a supply chain attack vector that's pretty effective. 

I ended up downloading and decompresisng the package to read through the code. Normally this is a fools errand as extension devs and/or malware devs minimize & obfuscate the code added to the store.  So I reached out here first to verify authenticity.
